version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/takeAway
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/logs/nginx-access.log:/var/log/nginx/access.log
      - ./.docker/logs/nginx-error.log:/var/log/nginx/error.log
    ports:
      - 8000:80      
    links:
      - php  

  php:    
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: php
    volumes:
      - .:/var/www/takeAway
    links:
      - mysql  

  mysql:
    image: mysql:8.0.2
    container_name: database
    ports:
      - 3308:3306
    environment:      
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}